# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_s_in21k_fold0 --options "model=tf_efficientnetv2_s_in21k" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_s_in21k_fold1 --options "model=tf_efficientnetv2_s_in21k" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_s_in21k_fold2 --options "model=tf_efficientnetv2_s_in21k" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_s_in21k_fold3 --options "model=tf_efficientnetv2_s_in21k" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_s_in21k_fold4 --options "model=tf_efficientnetv2_s_in21k" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"
#
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold0 --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold1 --options "model=efficientnet_b0" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold2 --options "model=efficientnet_b0" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold3 --options "model=efficientnet_b0" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold4 --options "model=efficientnet_b0" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"
#
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold0 --options "model=efficientnet_b3" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold1 --options "model=efficientnet_b3" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold2 --options "model=efficientnet_b3" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold3 --options "model=efficientnet_b3" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold4 --options "model=efficientnet_b3" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"

# python test.py config/resnet/resnet18_b16x8_xunfei_face.py --tag new_baseline_efficientnet_b0_fold_0 --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup.py --tag new_baseline_efficientnet_b0_fold_0 --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA.py --tag new_baseline_efficientnet_b0_fold_0 --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
#
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold0 --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold1 --options "model=efficientnet_b0" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold2 --options "model=efficientnet_b0" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"

python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b3_fold0_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b3_fold1_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b3_fold2_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b3_fold3_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b3_fold4_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"

python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold0_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold1_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold2_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold3_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold4_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"

python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold0_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold1_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold2_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold3_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold4_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"

python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold0_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold1_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold2_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
