# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_s_in21k_fold0 --options "model=tf_efficientnetv2_s_in21k" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_s_in21k_fold1 --options "model=tf_efficientnetv2_s_in21k" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_s_in21k_fold2 --options "model=tf_efficientnetv2_s_in21k" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_s_in21k_fold3 --options "model=tf_efficientnetv2_s_in21k" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_s_in21k_fold4 --options "model=tf_efficientnetv2_s_in21k" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"

# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_m_in21k_fold0 --options "model=tf_efficientnetv2_m_in21k" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_m_in21k_fold1 --options "model=tf_efficientnetv2_m_in21k" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_m_in21k_fold2 --options "model=tf_efficientnetv2_m_in21k" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_m_in21k_fold3 --options "model=tf_efficientnetv2_m_in21k" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_m_in21k_fold4 --options "model=tf_efficientnetv2_m_in21k" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"

# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_l_in21k_fold0 --options "model=tf_efficientnetv2_l_in21k" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_l_in21k_fold1 --options "model=tf_efficientnetv2_l_in21k" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_l_in21k_fold2 --options "model=tf_efficientnetv2_l_in21k" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_l_in21k_fold3 --options "model=tf_efficientnetv2_l_in21k" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag tf_efficientnetv2_l_in21k_fold4 --options "model=tf_efficientnetv2_l_in21k" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"

# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold0 --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold1 --options "model=efficientnet_b0" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold2 --options "model=efficientnet_b0" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold3 --options "model=efficientnet_b0" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold4 --options "model=efficientnet_b0" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"
#
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_test --options "model=efficientnet_b3" "data.train.ann_file=train_fold_demo.csv" "data.val.ann_file=valid_fold_demo.csv"
#
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold0 --options "model=efficientnet_b3" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold1 --options "model=efficientnet_b3" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold2 --options "model=efficientnet_b3" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold3 --options "model=efficientnet_b3" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold4 --options "model=efficientnet_b3" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"
#
#
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b4_fold0 --options "model=efficientnet_b4" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b4_fold1 --options "model=efficientnet_b4" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b4_fold2 --options "model=efficientnet_b4" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b4_fold3 --options "model=efficientnet_b4" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b4_fold4 --options "model=efficientnet_b4" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"
#
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b5_fold0 --options "model=efficientnet_b5" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b5_fold1 --options "model=efficientnet_b5" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b5_fold2 --options "model=efficientnet_b5" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b5_fold3 --options "model=efficientnet_b5" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b5_fold4 --options "model=efficientnet_b5" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"
#
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b6_fold0 --options "model=efficientnet_b6" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b6_fold1 --options "model=efficientnet_b6" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b6_fold2 --options "model=efficientnet_b6" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b6_fold3 --options "model=efficientnet_b6" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b6_fold4 --options "model=efficientnet_b6" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"
#
#
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b7_fold0 --options "model=efficientnet_b7" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b7_fold1 --options "model=efficientnet_b7" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b7_fold2 --options "model=efficientnet_b7" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b7_fold3 --options "model=efficientnet_b7" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b7_fold4 --options "model=efficientnet_b7" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"
#
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b8_fold0 --options "model=efficientnet_b8" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b8_fold1 --options "model=efficientnet_b8" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b8_fold2 --options "model=efficientnet_b8" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b8_fold3 --options "model=efficientnet_b8" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b8_fold4 --options "model=efficientnet_b8" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"

# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold0_baseline --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold1_baseline --options "model=efficientnet_b0" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold2_baseline --options "model=efficientnet_b0" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold3_baseline --options "model=efficientnet_b0" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold4_baseline --options "model=efficientnet_b0" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"
#
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag resnetv2_50x1_bitm_in21k_fold0 --options "model=resnetv2_50x1_bitm_in21k" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag resnetv2_50x3_bitm_in21k_fold0 --options "model=resnetv2_50x3_bitm_in21k" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag resnetv2_101x1_bitm_in21k_fold0 --options "model=resnetv2_101x1_bitm_in21k" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag resnetv2_101x3_bitm_in21k_fold0 --options "model=resnetv2_101x3_bitm_in21k" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag legacy_seresnext26_32x4d_fold0 --options "model=legacy_seresnext26_32x4d" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag legacy_seresnext50_32x4d_fold0 --options "model=legacy_seresnext50_32x4d" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag legacy_seresnext101_32x4d_fold0 --options "model=legacy_seresnext101_32x4d" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
#
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold0_baseline --options "model=efficientnet_b3" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold1_baseline --options "model=efficientnet_b3" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold2_baseline --options "model=efficientnet_b3" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold3_baseline --options "model=efficientnet_b3" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b3_fold4_baseline --options "model=efficientnet_b3" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"

#
# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag efficientnet_b0_fold_demo --options "model=efficientnet_b0" "data.train.ann_file=train_fold_demo.csv" "data.val.ann_file=valid_fold_demo.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup.py --tag efficientnet_b0_fold_demo --options "model=efficientnet_b0" "data.train.ann_file=train_fold_demo.csv" "data.val.ann_file=valid_fold_demo.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA.py --tag efficientnet_b0_fold_demo --options "model=efficientnet_b0" "data.train.ann_file=train_fold_demo.csv" "data.val.ann_file=valid_fold_demo.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag efficientnet_b0_fold_demo --options "model=efficientnet_b0" "data.train.ann_file=train_fold_demo.csv" "data.val.ann_file=valid_fold_demo.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_BNN_Neck.py --tag efficientnet_b0_fold_demo --options "model=efficientnet_b0" "data.train.ann_file=train_fold_demo.csv" "data.val.ann_file=valid_fold_demo.csv"

# python train.py config/resnet/resnet18_b16x8_xunfei_face.py --tag new_baseline_efficientnet_b0_fold_0 --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup.py --tag new_baseline_efficientnet_b0_fold_0 --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA.py --tag new_baseline_efficientnet_b0_fold_0 --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold0 --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"

# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_BNN_Neck.py --tag new_baseline_efficientnet_b0_fold0 --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_BNN_Neck.py --tag efficientnet_b0_fold_demo --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"

# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold0 --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold1 --options "model=efficientnet_b0" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold2 --options "model=efficientnet_b0" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold3 --options "model=efficientnet_b0" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold4 --options "model=efficientnet_b0" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"

# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b3_fold0_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b3_fold1_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b3_fold2_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b3_fold3_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b3_fold4_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"
#
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold0_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold1_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold2_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold3_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth.py --tag new_baseline_efficientnet_b0_fold4_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"

python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold0_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv" "resume_path=/home/muyun99/MyGithub/dyretrieval/work_dirs/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_tag_new_baseline_efficientnet_b3_fold0_120epoch/models/best.pth"
python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold1_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv" "resume_path=/home/muyun99/MyGithub/dyretrieval/work_dirs/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_tag_new_baseline_efficientnet_b3_fold1_120epoch/models/best.pth"
python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold2_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv" "resume_path=/home/muyun99/MyGithub/dyretrieval/work_dirs/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_tag_new_baseline_efficientnet_b3_fold2_120epoch/models/best.pth"
python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold3_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv" "resume_path=/home/muyun99/MyGithub/dyretrieval/work_dirs/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_tag_new_baseline_efficientnet_b3_fold3_120epoch/models/best.pth"
python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold4_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv" "resume_path=/home/muyun99/MyGithub/dyretrieval/work_dirs/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_tag_new_baseline_efficientnet_b3_fold4_120epoch/models/best.pth"

python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold0_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv" "resume_path=/home/muyun99/MyGithub/dyretrieval/work_dirs/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_tag_new_baseline_efficientnet_b0_fold0_120epoch/models/best.pth"
python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold1_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv" "resume_path=/home/muyun99/MyGithub/dyretrieval/work_dirs/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_tag_new_baseline_efficientnet_b0_fold1_120epoch/models/best.pth"
python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold2_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv" "resume_path=/home/muyun99/MyGithub/dyretrieval/work_dirs/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_tag_new_baseline_efficientnet_b0_fold2_120epoch/models/best.pth"
python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold3_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv" "resume_path=/home/muyun99/MyGithub/dyretrieval/work_dirs/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_tag_new_baseline_efficientnet_b0_fold3_120epoch/models/best.pth"
python train.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold4_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv" "resume_path=/home/muyun99/MyGithub/dyretrieval/work_dirs/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_tag_new_baseline_efficientnet_b0_fold4_120epoch/models/best.pth"

# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold0_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold1_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold2_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold3_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b3_fold4_120epoch --options "model=efficientnet_b3" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"


# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold0_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold0.csv" "data.val.ann_file=valid_fold0.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold1_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold1.csv" "data.val.ann_file=valid_fold1.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold2_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold2.csv" "data.val.ann_file=valid_fold2.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold3_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold3.csv" "data.val.ann_file=valid_fold3.csv"
# python test.py config/resnet/resnet18_b16x8_xunfei_face_warmup_REA_Label_smooth_bigger_size.py --tag new_baseline_efficientnet_b0_fold4_120epoch --options "model=efficientnet_b0" "data.train.ann_file=train_fold4.csv" "data.val.ann_file=valid_fold4.csv"